# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('nature', 'Nature'), ('architecture', 'Architecture'), ('entertainment', 'Entertainment')], default='history', max_length=13),
        ),
    ]
