# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-02-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_trip_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='youtube_url',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
