# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-02-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20170207_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
